### ISSUE TITLE
maybe *$stdout*... is more accurate

### ISSUE THREAD

**Issue by pulgamecanica** [leastbad/optimism#34]
https://github.com/leastbad/optimism/blob/de6858a9828780d3211370addd41fce2163953ea/lib/optimism/rake.rb#L19
....
I just wanted to point out that it might be more accurate to use *$stdout*... Im just a noob and I know it doesn't changes any functionality... haha I was just having a look at the cool Ruby files.
I will delete this issue soon because it's not an issue..... haha I just felt like sharing this....

**Comment by leastbad** [comment]
Hi Andre! Welcome and don't ever apologize for posting suggestions in good faith.

Soooo, I did a `git blame` and this functionality was contributed by @andrewmcodes, who is no slouch but also is in a better position to explain why he chose to use `$stderr`.

**Comment by andrewmcodes** [comment]
hm I’m not sure why I choose `$stderr` since that is typically reserved for exceptions. I must have copied and pasted some code without thinking about it too much. You’re correct that `$stdout` would be semantically more “correct” though I’m not sure the actual implementation would change much. 

PR’s accepted.

**Comment by leastbad** [comment]
@pulgamecanica it seems like you could make a PR......... 💯

**Comment by pulgamecanica** [comment]
Amazing, I feel so honored, this will be my very first "contribution" as little as it is, but Im very happy! :)

**Comment by leastbad** [comment]
Just to be clear, it's us that is lucky to entertain someone's first PR. Bravo, friend!
