### ISSUE TITLE
Usage with simple_form and bootstrap

### ISSUE THREAD

**Issue by adambedford** [leastbad/optimism#39]
Has anyone had success getting Optimism hooked up to Simple Form? It'd be awesome to generate the necessary markup automatically in the form builder.

**Comment by leastbad** [comment]
Hi Adam!

We actually had a discussion about this just the other day on the Discord: https://discordapp.com/channels/681373845323513862/681374031773302844/849335300018667547

I'm going to close this because while we're happy to discuss all of your questions about SF on Discord, the question itself is not an Issue.
